### ISSUE TITLE
Incorrect property for YouTubeUser

### ISSUE THREAD

**Issue by madashio** [SocialBlade/socialblade-js#13]
The api response for the YouTube user contains `statistics.growth.vidviews` but the interface `statistics.growth.views`

Library Version: 1.0.3,

Node Version :v18.13.0

**Comment by timcole** [comment]
Hello, thanks for bringing this to our attention, it actually appears this is an issue caused by the API side, it was views for it appears it was mistakenly switched to `vidviews`.

That said, we will leave the API response as is since it was switched a bit ago now and will get the library updated instead to prevent breaking changes in the API itself.

**Comment by timcole** [comment]
Fixed in be6b773656efa2d5e9b16b56162949197e987aea, v1.0.4 published to npm. Thanks again for the report! 👍🏻
